### PR TITLE
Depend on DocumentTemplate 3.1+ to do SQL quoting [master]

### PR DESCRIPTION
**Pull request by mauritsvanrees**
From PloneHotfix20200121.
See also https://github.com/zopefoundation/DocumentTemplate/pull/46

### CODE REVIEW

**Comment by mauritsvanrees** [comment]
Looks good now. I apparently forgot to run the tests again after my last commit. And then I prepared a similar fix, but lost internet connection.

**Comment by dataflake** [comment]
Release 3.0.11 is now on PyPI

**Comment by mauritsvanrees** [comment]
Thank you for the quick reviews and releases!

**Comment by dataflake** [comment]
No, thank you for doing these PRs so quickly. Makes it real easy for me.

**Pull request merged**
