### PR TITLE
Show rendered SQL in error case; issue #15

### PR DESCRIPTION
**Pull request by mvoppen**
Fixes issue #15
New feature to display the rendered SQL query also in error case where it is most helpful.

### CODE REVIEW

**Comment by dataflake** [comment]
@igs165 Have you signed either the Zope Foundation contributor agreement or the new Plone Foundation agreement? It doesn't look like it. Please see https://www.zope.org/developer/becoming-a-committer.html and finish that process before anyone here can merge your contribution.

**Comment by igs165** [comment]
I've filed the Contributer agreement to agreements@plone.org now. That was not so easy as agreements@plone.org aka Google Groups rejected all emails as Spam. Maybe I should open an issue that plone.org should search for a more serious and reputable email provider.

**Comment by dataflake** [comment]
I'll look at this tonight or tomorrow. This is missing a change log entry.

**Comment by dataflake** [comment]
I fixed this in 128cd973547063c91c157b67e6cce44b9e1aa4cf.

**Pull request closed without merging**
