### PR TITLE
fix HTML quoting in ZSQL test forms

### LINKED ISSUE #44: ZSQL Test Forms do no HTML escaping
### What I did:

I added a ZSQLMethod in ZMI with this statement (I use a Oracle DB):

`select 'a<xyz>b' VALUE from dual`

sql-01

and clicked on the "Test" tab.

### What I expect to happen:

That the Value `a<xyz>b` is shown.

### What actually happened:

In the browser i see the value `ab` (instead of `a<xyz>b`). Both in the query and in the result table:

sql-02

### What version of Python and Zope/Addons I am using:

Zope-5.9
Python-3.9.5
Products.ZSQLMethods-4.0

### Additional Info

It seems that the "html_quote" is missing in some DTML reports. I will provide a PR with a fix and tests...

### PR DESCRIPTION
**Pull request by wlang42**
fixes #44

### CODE REVIEW

**Comment by wlang42** [comment]
fixes #44

**Comment by dataflake** [comment]
It looks like you have not signed the contributor agreement yet, Could you please do so? See https://www.zope.dev/developer/becoming-a-committer.html for details.

**Comment by wlang42** [comment]
> It looks like you have not signed the contributor agreement yet, Could you please do so? See https://www.zope.dev/developer/becoming-a-committer.html for details.

Sure, done.

**Review by dataflake — APPROVED** [review]
Thank you!

**Comment by dataflake** [comment]
Please go ahead and merge

**Pull request merged**
